spring:
  jpa.hibernate.ddl-auto: create-drop
  jackson.serialization.INDENT_OUTPUT: true
server:
  contextPath: /lincsproteomics
  port: 8050

urls:
  pilincsApiTags: http://eh3.uc.edu/pilincs/api-tags
  pilincsP100Api: http://eh3.uc.edu/pilincs/api-assays-paged/?order=asc&limit=100000&offset=0&tags=[{"name":"%s","flag":"Perturbation","annotation":"Pertiname"},{"p100":true}]
  stringNetworkJSON: https://string-db.org/api/json/network?identifiers=%s
  stringNetworkSVG: https://string-db.org/api/image/network?identifiers=%s
  harmonizomeGene: http://amp.pharm.mssm.edu/Harmonizome/api/1.0/gene/%s
  pythonP100Api: http://127.0.0.1:5000/api/clust/P100/aggregatedforSlicing/%s
  pythonGCPApi: http://127.0.0.1:5000/api/clust/GCP/aggregatedforSlicing/%s
  downloadP100Api: http://127.0.0.1:5000/api/P100/downlowdslice/%s
  downloadGCPApi: http://127.0.0.1:5000/api/GCP/downlowdslice/%s

resources:
  mapping: /psi-mod/mapping.csv
  pcg: /PCG/pcgm.json
  kinase2GeneHuman: /kinase/kinase2Gene_human.json
  gene2KinaseHuman: /kinase/gene2Kinase_human.json
  geneName2KinaseName: /kinase/geneName2KinaseName_human.json
  compoundInfo: /static/data/proteomics_compound_info.json
  representativeCompoundInfo: /static/data/phiQlust_representative_info.json
  proteomicsLSMWithFingerprint: /static/data/proteomicsLSMWithFingerprint.json
  LSMCSVFile: src/main/resources/static/data/SmallMolecule2.csv


---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost/pln
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect