spring:
  jpa.hibernate.ddl-auto: create-drop
  jackson.serialization.INDENT_OUTPUT: true
server:
  contextPath: /plp
  port: 8050

urls:
  prosite: http://prosite.expasy.org/cgi-bin/prosite/PSScan.cgi?sig=%s&lineage=9606&db=sp&output=json
  uniprot: http://www.uniprot.org/uniprot/%s.xml?query=reviewed:yes+AND+organism:9606
  enrichrAddList: http://amp.pharm.mssm.edu/Enrichr/addList
  enrichrViewList: http://amp.pharm.mssm.edu/Enrichr/view?userListId=%s
  enrichrResult: http://amp.pharm.mssm.edu/Enrichr/enrich?userListId=%s&backgroundType=%s
  enrichrGeneInfo: http://amp.pharm.mssm.edu/Enrichr/genemap?json=true&setup=true&gene=%s


resources:
  mapping: /psi-mod/mapping.csv
  pcg: /PCG/pcgm.json
  kinase2GeneHuman: /kinase/kinase2Gene_human.json
  gene2KinaseHuman: /kinase/gene2Kinase_human.json
  geneName2KinaseName: /kinase/geneName2KinaseName_human.json


---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost/pln
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect